version: '3'
services:
 broker-rabbitmq:
   image: "rabbitmq:3.9.13-management"
   ports:
     - "15673:15672"
   environment:
     - RABBITMQ_DEFAULT_USER=rabbit_user
     - RABBITMQ_DEFAULT_PASS=rabbit_password
   networks:
     - techeer
 db-postgres:
   image: "postgres:11.2"
   environment:
     - POSTGRES_USER=db_user
     - POSTGRES_PASSWORD=db_password
   networks:
     - techeer
 api:
   build: .
   command: gunicorn --workers=10 --bind 0.0.0.0:8888 wsgi:app
   ports:
    - "8888:8888"
   environment:
     - APP_ENV=${APP_ENV}
   depends_on:
     - broker-rabbitmq
     - db-postgres
   volumes:
     - .:/flask-deploy
   networks:
     - techeer
 api-worker01:
   build: .
   command: watchmedo auto-restart --directory=./ --pattern=*.py --recursive -- celery -A tasks.celery worker --loglevel=info
   environment:
     - APP_ENV=${APP_ENV}
   depends_on:
     - broker-rabbitmq
     - db-postgres
   volumes:
     - .:/flask-deploy
   networks:
     - techeer
 api-worker02:
   build: .
   command: watchmedo auto-restart --directory=./ --pattern=*.py --recursive -- celery -A tasks.celery worker --loglevel=info
   environment:
     - APP_ENV=${APP_ENV}
   depends_on:
     - broker-rabbitmq
     - db-postgres
   volumes:
     - .:/flask-deploy
   networks:
     - techeer
 api-beat:
   build: .
   command: celery -A tasks.celery beat --loglevel=info
   environment:
     - APP_ENV=${APP_ENV}
   depends_on:
     - broker-rabbitmq
     - db-postgres
   networks:
     - techeer
 celery-flower:
   image: gregsi/latest-celery-flower-docker:latest
   environment:
     - AMQP_USERNAME=rabbit_user
     - AMQP_PASSWORD=rabbit_password
     - AMQP_ADMIN_USERNAME=rabbit_user
     - AMQP_ADMIN_PASSWORD=rabbit_password
     - AMQP_HOST=broker-rabbitmq
     - AMQP_PORT=5672
     - AMQP_ADMIN_HOST=broker-rabbitmq
     - AMQP_ADMIN_PORT=15672
     - FLOWER_BASIC_AUTH=user:test
   ports:
     - "5556:5555"
   depends_on:
     - broker-rabbitmq
   networks:
     - techeer
 nginx:
   build: ./nginx
   ports:
     - 1337:80
   volumes:
     - ./build:/build/
   depends_on:
     - api
   networks:
     - techeer

networks:
 techeer:
   driver: bridge