version: '3'
services:
 broker-rabbitmq:
   image: "rabbitmq:3.9.13-management"
   ports:
     - "15673:15672"
   environment:
     - RABBITMQ_DEFAULT_USER=rabbit_user
     - RABBITMQ_DEFAULT_PASS=rabbit_password
   expose:
     - 5672
   networks:
     - techeer
 db-postgres:
   image: "postgres:11.2"
   environment:
     - POSTGRES_USER=db_user
     - POSTGRES_PASSWORD=db_password
   networks:
     - techeer
 api:
   build: .
   command: gunicorn --workers=10 --bind 0.0.0.0:8888 wsgi:app
   ports:
    - "8888:8888"
   environment:
     - APP_ENV=${APP_ENV}
   depends_on:
     - broker-rabbitmq
     - db-postgres
   volumes:
     - .:/flask-deploy
   networks:
     - techeer
 api-worker01:
   build: .
   command: watchmedo auto-restart --directory=./ --pattern=*.py --recursive -- celery -A tasks.celery worker --loglevel=info
   environment:
     - APP_ENV=${APP_ENV}
   depends_on:
     - broker-rabbitmq
     - db-postgres
   volumes:
     - .:/flask-deploy
   networks:
     - techeer
 api-worker02:
   build: .
   command: watchmedo auto-restart --directory=./ --pattern=*.py --recursive -- celery -A tasks.celery worker --loglevel=info
   environment:
     - APP_ENV=${APP_ENV}
   depends_on:
     - broker-rabbitmq
     - db-postgres
   volumes:
     - .:/flask-deploy
   networks:
     - techeer
 api-beat:
   build: .
   command: celery -A tasks.celery beat --loglevel=info
   environment:
     - APP_ENV=${APP_ENV}
   depends_on:
     - broker-rabbitmq
     - db-postgres
   networks:
     - techeer
 flower:
   image: mher/flower:0.9.7
   command: ['flower', '--broker=amqp://rabbit_user:rabbit_password@broker-rabbitmq:5672', '--port=5555']
   ports:
     - 5555:5555
   depends_on:
     - broker-rabbitmq
   networks:
     - techeer
 nginx:
   build: ./nginx
   ports:
     - 1337:80
   volumes:
     - ./build:/build/
   depends_on:
     - api
   networks:
     - techeer

networks:
 techeer:
   driver: bridge